export const RELIABILITY_CONFIG = {
  POPULATION_DELIVERY_SUCCESS: 0.7,
  DELIVERY_PSEUDO_ORDERS: 5,
  CONFIRMATION_PSEUDO_CALLS: 3,
  POPULATION_CONFIRMATION_SUCCESS: 0.6,
  HALF_LIFE_DAYS: 180,
  TIER_FIABLE: 75,
  TIER_SURVEILLER: 50,
  MIN_DECIDED: 3,
  PROVISIONAL_MAX: 5,
} as const;

export const {
  CONFIRMATION_PSEUDO_CALLS,
  DELIVERY_PSEUDO_ORDERS,
  HALF_LIFE_DAYS,
  MIN_DECIDED,
  POPULATION_CONFIRMATION_SUCCESS,
  POPULATION_DELIVERY_SUCCESS,
  PROVISIONAL_MAX,
  TIER_FIABLE,
  TIER_SURVEILLER,
} = RELIABILITY_CONFIG;
